var townNames = [
	"Adurant",
	"Aenor’ s Hill",
	"Aerilon",
	"Amram",
	"Anfauglith",
	"Aquarin",
	"Aramoor",
	"Arlan’ s Way",
	"Arnor",
	"Arrendyll",
	"Ashdrift",
	"Avaglade",
	"Azmar",
	"Battlecliff",
	"Bay of Balar",
	"Begger’ s Hole",
	"Beleriand",
	"Black Hollow",
	"Blue Field",
	"Boatwright",
	"Briar Glen",
	"Brickelwhyte",
	"Brilthor",
	"Broken Shield",
	"Bruinen",
	"Bullmar",
	"Camorrus",
	"Carran",
	"City of Fire",
	"Coalfell",
	"Corralis",
	"Crow’ s Cry",
	"Cullfield",
	"Darendale",
	"Darkwell",
	"Deathfall",
	"Death’ s Door",
	"Dimbar",
	"Doonatel",
	"Doriath",
	"Dorlomin",
	"Dorthonion",
	"Doveseal",
	"Doveshire",
	"Dragon’ s Coast",
	"Dry Gulch",
	"Duarudelf",
	"Duskendale",
	"East Armistice",
	"Eastford",
	"Easthaven",
	"Eastwatch",
	"Ecrin",
	"Eden’ s Gulf",
	"Ekaia",
	"Elbright",
	"Eldarmar",
	"Embertown",
	"End’ s Run",
	"Erast",
	"Ered",
	"Erede",
	"Eredluin",
	"Eribourne",
	"Ethermoor",
	"Fallenedge",
	"Fangorn",
	"Far Water",
	"Firebend",
	"Firecrow",
	"Fool’ s March",
	"Freevale",
	"Frostenvale",
	"Frostfangs",
	"Frostford",
	"Garen’ s Well",
	"Glaskerville",
	"Goldcrest",
	"Goldenleaf",
	"Greenflower",
	"Greenglade",
	"Greenloft",
	"Gulltown",
	"Haran",
	"Harlen",
	"Harsengaard",
	"Hillfar",
	"Hogsfeet",
	"Hollyhead",
	"Horizon’ s End",
	"Hull",
	"Hwen",
	"Icemeet",
	"Iron Hills",
	"Ironforge",
	"Irragin",
	"Jarren’ s Outpost",
	"Jongvale",
	"Kara’ s Vale",
	"Knife’ s Edge",
	"Lakeshore",
	"Lakestown",
	"Lamorra",
	"Last Lock",
	"Leeside",
	"Legolin",
	"Linesse",
	"Lochley",
	"Lothlann",
	"Lullin",
	"Maglor’ s Gap",
	"Mahalaga",
	"Marren’ s Eve",
	"Merriwich",
	"Millstone",
	"Moonbright",
	"Mountmend",
	"Nandungorteb",
	"Nargorthon",
	"Nearon",
	"New Cresthill",
	"Nogrod",
	"Northpass",
	"Northstead",
	"Northtown",
	"Nuxvar",
	"Oakensword",
	"Oakheart",
	"Oar’ s Rest",
	"Old Ashton",
	"Orrinshire",
	"Ozryn",
	"Pavv",
	"Pella’ s Wish",
	"Pineland",
	"Pinnella Pass",
	"Pony Run",
	"Pran",
	"Pyreacre",
	"Quan Ma",
	"Queenstown",
	"Ramshorn",
	"Red Hawk",
	"Rhaunar",
	"Rhudaur",
	"Rhuin",
	"Rivermouth",
	"Riverwind",
	"Saker Keep",
	"Seameet",
	"Shadestown",
	"Shiny Ship",
	"Ship’ s Haven",
	"Silverkeep",
	"Snake’ s Canyon",
	"Snowforge",
	"Snowmelt",
	"South Warren",
	"Southern Vale",
	"Squall’ s End",
	"Stone’ s Throw",
	"Stonewatch",
	"Strong Oak",
	"Suilwen",
	"Sundance",
	"Swordbreak",
	"Tarrin",
	"Taur - in -duinath",
	"Thales",
	"The Gale",
	"The Last Battle",
	"Three Streams",
	"Trudid",
	"Ubbin Falls",
	"Ula’ ree",
	"Vale of Doom",
	"Valley of Dusk",
	"Veritas",
	"Vertrock",
	"Violl’ s Garden",
	"Wolfsrealm",
	"Wellspring",
	"Westend",
	"Westwend",
	"Whiteridge",
	"Whiterun",
	"Widow’ s Peak",
	"Willowdale",
	"Windrip",
	"Wintergale",
	"Wintervale",
	"Wolfden",
	"Xan’ s Bequest",
	"Xynnar",
	"Yarrin",
	"Yellowseed",
	"Yi Ti",
	"Zao Ying",
	"Zeffari",
	"Zumka",
	"Sonsha",
	"Lonwi",
	"Weto",
	"Yamao",
	"Winlon",
	"Sinya",
	"Sonwi",
	"Mentai",
	"Zokswi",
	"Cannach",
	"Simiral",
	"Fleanor",
	"Glandolia",
	"Perser",
	"Bregalad",
	"Ninole",
	"Aribmuloc",
	"Elin",
	"Falmat",
	"Calesaxon",
	"Mersever",
	"Cardisea",
	"Thamwold",
	"Angloria",
	"Naviot",
	"Esterlin",
	"Munlech",
	"Goult",
	"Isvrachen",
	"Lithesen",
	"Yuglasen",
	"Drachen",
	"Teumanis",
	"Cthonia",
	"Lycedion",
	"Sarmania",
	"Cthandocia",
	"Korsika",
	"Kilstonine",
	"Rankor",
	"Ytterheim",
	"Cassrio",
	"Mauro",
	"Mestauskalio",
	"Shipton",
	"Mournstead",
	"Burnsley",
	"Horndean",
	"Pathstow",
	"Violl 's Garden",
	"Narthwich",
	"Halsworthy",
	"Burrafirth",
	"Larnwick",
	"Skargness",
	"Butterpond",
	"Lowestoft",
	"Ritherhithe",
	"Garigill",
	"Aylesbury",
	"Auchendale",
	"Newham",
	"Leurbost",
	"Ferncombe",
	"Armskirk",
	"Cromerth",
	"Murkwell",
	"Beckinsale",
	"Woodhaerst",
	"Acrine",
	"Wealdstone",
	"Glanchester",
	"Kilkenny",
	"Pontybridge",
	"Cardended",
	"Rotherhithe",
	"Cherrytown",
	"Ilfreycombe",
	"Hampford",
	"Hankala",
	"Farnfoss",
	"Niska",
	"Aermagh",
	"Perlshaw",
	"Streatham",
	"Aberystwyth",
	"Calcherth",
	"Armagh",
	"Addersfield",
	"AHearn",
	"Abante",
	"Abastumani",
	"Abell",
	"Abetti",
	"Abkhazia",
	"Abnoba",
	"Abundantia",
	"Academia",
	"Achaia",
	"Achilles",
	"Aconcagua",
	"Ada",
	"Adalberta",
	"Binzel",
	"Birch",
	"Birgit",
	"Birgitta",
	"Biryukov",
	"Budrosa",
	"Bulgakov",
	"Chaika",
	"Chaka",
	"Chaldaea",
	"Chalonge",
	"Champollion",
	"Chandra",
	"Chang",
	"Chant",
	"Chantal",
	"Chapleya",
	"Chaplin",
	"Chapman",
	"Dante",
	"Danubia",
	"Danzig",
	"Daphne",
	"Eupraksia",
	"Euripides",
	"Europa",
	"Euryanthe",
	"Eurydike",
	"Eurykleia",
	"Eurynome",
	"Euterpe",
	"Eva",
	"Evans",
	"Evdokiya",
	"Evelyn",
	"Evenkia",
	"Everhart",
	"Evita",
	"Fabiola",
	"Fabre",
	"Faina",
	"Fama",
	"Fanale",
	"Fanatica",
	"Fanny",
	"Fantasia",
	"Farinella",
	"Fatme",
	"Fatyanov",
	"Fayeta",
	"Fedchenko",
	"Fedynskij",
	"Feldman",
	"Felicia",
	"Felicitas",
	"Gibbs",
	"Gibson",
	"Giclas",
	"Gilgamesh",
	"Ginevra",
	"Gingerich",
	"Halliday",
	"Hallstrom",
	"Haltia",
	"Hamburga",
	"Hameenlinna",
	"Hamiltonia",
	"Hamina",
	"Hammonia",
	"Handahl",
	"Handel",
	"Hanko",
	"Ilinsky",
	"Iliya",
	"Illyria",
	"Ilmari",
	"Ilmatar",
	"Ilona",
	"Ilse",
	"Ilsebill",
	"Justus",
	"Jutta",
	"Juvisia",
	"Jyvaskyla",
	"Kaarina",
	"Kacha",
	"Kacivelia",
	"Kafka",
	"Kahrstedt",
	"Kaiser",
	"Kajaani",
	"Kakhovka",
	"Kalahari",
	"Kalbaugh",
	"Kalevala",
	"Kalinin",
	"Ladoga",
	"Laetitia",
	"Lagerkvist",
	"Lagrangea",
	"Lagrula",
	"Lahti",
	"Lalage",
	"Lamber"
]
var townDescList = [
	'a quaint village',
	'a small town',
	'a big town',
	'a starving village',
	'a mining village',
	'a fishing village'
]
var townLocationList = [
	'on the side of a sauntering river',
	'blocking the mouth of a large cave',
	'in the middle of a desert',
	'nestled in a clearing, in the middle of the woods',
	'on the outskirts of a much larger city',
	'on the border of the nation',
	'by the seaside',
	'atop a mountain'
]

function getRandomTownName() {
	newTownName = townNames[Math.floor(Math.random() * townNames.length)];
	return newTownName;
}

function getTownShortDesc() {
	shortDescription = townDescList[Math.floor(Math.random() * townDescList.length)];
	return shortDescription;
}

function getTownLocation() {
	townLocation = townLocationList[Math.floor(Math.random() * townLocationList.length)];
	return townLocation;
}